Navigation 구현 및 custom dialog 구현
thingsflow/android-intern-practice pull request #8
Opened 2022-04-01 08:05 UTC by dycha0430

Navigation을 공부하고 코드에 적용하였습니다.
그리고 제목을 누르면 organization과 repository의 입력을 받는 것을 구현하였는데, 입력을 하면 viewmodel 내의 livedata들의 값이 변하는 것은 확인이 되지만 livedata들이 ui를 자동으로 업데이트해주지 않네요 ㅠㅠ 아직 이유를 찾지 못해서 더 공부해보아야할 것 같은데, 혹시 관련해서 도움을 조금 받을 수 있을까요..?

2022-04-03 05:01 UTC, gyeongmunbaek requested changes
요청하신 부분에 대해 답변을 달아놨습니다 :)

2022-04-03 05:01 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/InputDialog.kt
> +    private val viewModel: MainViewModel by viewModels()
이렇게 선언하시면 Activity의 ViewModelProvider를 사용하지 않으므로 별개의 뷰모델이 생성되어 이 다이얼로그에서만 사용하는 뷰모델이 되겠군요. 뷰모델의 공유를 위해서는 activityViewModels()를 사용해보세요 :)

2022-04-04 02:06 UTC, dycha0430 commented on app/src/main/java/com/thingsflow/internapplication/ui/main/InputDialog.kt
> +    private val viewModel: MainViewModel by viewModels()
말씀해주신 부분을 통해 문제를 해결하였습니다. 감사합니다:)
그리고 몇가지 남은 부분을 더 진행하여 과제 명세 중 상세 내용에 적힌 내용들은 모두 구현을 한 것 같은데, 혹시 더 수정해야 할 부분이 있는지 확인해 주실 수 있으실까요..?
혹시 더 필요한 사항이 없다면 이후에는 명세의 선택 사항을 진행하면 될까요?

2022-04-04 04:40 UTC, gyeongmunbaek approved these changes
👍

2022-04-04 04:40 UTC, merged