Hilt, retrofit setup and load issue data
thingsflow/android-intern-practice pull request #9
Opened 2022-04-01 09:08 UTC by jjminsuh

- navigation 설정 마무리했습니다.
- hilt, retrofit 관련 공부 진행했고, recyclerview 부분을 추가하여 navigation 연결 진행했습니다.
- network 이용하여 issue data를 가져오는 부분 진행 중입니다.
- 오늘 메인 화면에 issue data 목록을 가져오는 것을 확인했는데, 앱을 종료 후 다시 실행 시 data를 가져오는 데 시간이 오래걸리는 문제가 발생하여 이와 관련하여 자료를 찾아보고 있는 중입니다.

2022-04-03 05:08 UTC, gyeongmunbaek requested changes

2022-04-03 05:08 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainViewModel.kt
> +        _issueList.value = ArrayList()
굳이 리스트를 초기화할 필요는 없을 것 같습니다.

2022-04-03 05:08 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainViewModel.kt
> +                _issueList.value = ArrayList(it)
여기도 어차피 데이터가 동일하니 다시 어레이리스트 객체로 생성해서 넣을 필요는 없을 것 같아요.

2022-04-04 09:00 UTC, jjminsuh commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainViewModel.kt
> +                _issueList.value = ArrayList(it)
- 말씀해주신 부분 수정 후 작업 진행했습니다.
- RecyclerView에 banner와 url 이동 기능 추가했고,
- detail 페이지에 상세 내용 띄우는 부분 진행했습니다.

2022-04-04 10:46 UTC, gyeongmunbaek requested changes
코멘트 확인해주세요~ 오늘도 고생하셨습니다!

2022-04-04 10:46 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/detail/IssueDetailFragment.kt
> +        val userID = viewModel.issueList.value?.get(issuePos)?.userInfo?.userId
viewModel에 있는 객체에 바로 접근하시기보단 옵저빙하는 방식을 추천합니다.
따라서 viewModel에 현재 선택된 이슈에 대한 객체를 만드시고 이 프레그먼트에 접근하면 해당 객체를 옵저빙해서 화면에 뿌려주면 좋을 것 같습니다.

2022-04-04 10:46 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/IssueListAdapter.kt
> +            holder.bind(currentList[position - 1], (position - 1))
아답터에서 인덱트를 이용하여 바인딩 분기를 태우는 것보단 리스트 아이템의 타입에 따라 분기를 시키는 것이 좋습니다. 그러면 position - 1 과 같은 음? 하는 코드가 발생하지 않고 향후 새로운 타입이 추가되도 문제가 될 여지가 적습니다.예를 들면 아래와 같습니다.

```
sealed class Item {
    data class Issue(
        val ...
    ) : Item()

    data class Image(
        val url: String
    ) : Item()
}
```
위와 같은 형태라면 Item을 아답터에서 받아서 is Issue, is Image 등의 타입으로 구별이 가능합니다. Item으로 이뤄진 리스트는 뷰모델에서 만들어오면 되겠지요.

2022-04-04 10:46 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainFragment.kt
> +        val title = binding.title
굳이 변수를 추가할 필욘 없어 보이네요. 
```
binding.title.setOnClickListener {
            showDialog()
        }
```
여도 충분히 보입니다.

2022-04-04 10:46 UTC, gyeongmunbaek commented on app/src/main/res/layout/main_fragment.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
ConstraintLayout의 중첩 없이 한번 해보시겠어요? :)

2022-04-05 03:55 UTC, gyeongmunbaek requested changes
코멘트 확인해주시고 해결한 요청에 대해서는 Resolve 처리도 해주세요.

2022-04-05 03:55 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/IssueListCallBack.kt
> +        return oldItem == newItem
타입별로 구분해서 내부에 있는 변수를 비교해주세요.

2022-04-05 03:55 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainFragment.kt
> +        viewModel.setIssueList("google", "dagger")
setOrganization, setRepository setIssueList 셋 다 호출하는 것보단 setOrganization과 setRepository 또는 setIssueList 만으로 동일한 기능을 할 수 있도록 하면 좋을 것 같습니다.

2022-04-05 03:55 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainFragment.kt
> +    fun Group.setGroupOnClickListener(listener: View.OnClickListener){
이거 혹시 아이템 클릭했을 때 동작인가요? 만약 그렇다면 adapter에서 이벤트 받고 -> viewModel -> view -> 이동으로 처리할 수 있으면 좋을 것 같습니다.

2022-04-05 03:55 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainViewModel.kt
> +                itemList.add(POS, Item.Image(BANNER_IMG_URL))
it의 사이즈가 POS보다 적을 때의 처리가 있음 좋겠네요.

2022-04-05 05:01 UTC, jjminsuh commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainFragment.kt
> +    fun Group.setGroupOnClickListener(listener: View.OnClickListener){
제목 부분 클릭했을 때의 동작을 위해서 추가한 함수입니다. 
위의 중첩 ConstraintLayout 관련 부분을 해결하기 위해 xml에서 Group을 활용했고,
3개의 textView로 이루어져 있는 제목의 어느 부분을 클릭하더라도 팝업을 띄울 수 있도록 하는 함수입니다.
(Group 자체에는 setOnClickListener를 사용할 수 없다고 하여 함수를 추가했습니다.)
이 방식이 좋은 방식인지 잘 모르겠습니다. 혹시 더 나은 방법이 있을까요?

2022-04-05 06:38 UTC, jjminsuh commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainFragment.kt
> +    fun Group.setGroupOnClickListener(listener: View.OnClickListener){
제목 부분 textView를 한 개로 수정하는 것이 더 좋은 방법인 것 같아 다시 수정했습니다.

2022-04-05 09:46 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/MainFragment.kt
> +    fun Group.setGroupOnClickListener(listener: View.OnClickListener){
@jjminsuh 오 제목이라면, 적합한 방법입니다. 정상 동작한다면 된거죠 :)

2022-04-05 09:47 UTC, gyeongmunbaek approved these changes
👍

2022-04-05 09:56 UTC, gyeongmunbaek requested changes
아답터 부분 체크해주세요.

2022-04-05 09:56 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/IssueListAdapter.kt
> +                val action = MainFragmentDirections.actionMainToDetail(position)
민서님께서도 이 클릭 이벤트를 아답터 -> 뷰모델 -> 뷰에서 처리할 수 있는 방법을 고민해보시기 바랍니다.
좀 더 힌트를 드리면 인터페이스를 하나 선언해서 아답터 생성 시 콜백을 등록하시고, 인터페이스를 통해 클릭 이벤트를 받으면 뷰모델로 전달. 그 후에 옵저버를 통해 네비게이션 동작. 입니다.
뷰모델의 MutableData는 지속적인 관찰보단 온클릭과 같은 일회성 이벤트를 처리하기 용이한 형태가 필요한데요.
https://woochan-dev.tistory.com/86 이 블로그를 참고하셔서 구성해보심 좋을 것 같습니다.

2022-04-06 05:09 UTC, gyeongmunbaek approved these changes

2022-04-06 05:09 UTC, gyeongmunbaek commented on app/src/main/java/com/thingsflow/internapplication/ui/main/Event.kt
> +}
```
class EventObserver<T>(private val onEventUnhandledContent: (T) -> Unit) : Observer<Event<T>> {
    override fun onChanged(event: Event<T>?) {
        event?.getContentIfNotHandled()?.let {
            onEventUnhandledContent(it)
        }
    }
}

```

2022-04-07 00:51 UTC, merged